version: "3"
services:
  kong1:
    build: .
    environment:
      - ENV=dev
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/decrelative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout custom_format
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_LOG_LEVEL=debug
    command: >
      /bin/bash -c "kong start"
    restart: on-failure
    ports:
      - 8001:8000
    networks:
      - kong-net

  kong2:
    build: .
    environment:
      - ENV=dev
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/decrelative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout custom_format
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_LOG_LEVEL=debug
    command: >
      /bin/bash -c "kong start"
    restart: on-failure
    ports:
      - 8002:8000
    networks:
      - kong-net

  kong3:
    build: .
    environment:
      - ENV=dev
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/decrelative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout custom_format
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_LOG_LEVEL=debug
    command: >
      /bin/bash -c "kong start"
    restart: on-failure
    ports:
      - 8003:8000
    networks:
      - kong-net

  konga:
    image: pantsel/konga
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 1337:1337
    networks:
      - kong-net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - kong-net
    depends_on:
      - kong1
      - kong2
      - kong3

networks:
  kong-net:
    driver: bridge